### ISSUE TITLE
Prepared first iteration of analysis-ready (processed) data”.

### ISSUE THREAD

**Issue by AaronKip-42** [ds4owd-001/project-Aaron-Kipngeno#1]
i am trying to save processed data , in  required folder, 

here is error
write.csv(sanitation_clean, "data/processed/sanitation_clean.csv")

_**Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection**_
@larnsce @mianzg @sskorik01

**Comment by larnsce** [comment]
Thanks for your question, @AaronKip-42.

When you want to write the processed file, use `write_csv()` instead of `write.csv()`. That doesn't fix your error, which is due to the file path. Check what you have done for reading the data in and try to apply the same for writing the processed data:

https://github.com/ds4owd-001/project-Aaron-Kipngeno/blob/df05031f1963da618e37325394ac02df8c1bd914/docs/index.qmd#L34

**Comment by AaronKip-42** [comment]
kindly help on how to add error bar.
#bar graph for education with error bar.

ggplot(sanitation_clean, aes(education)) +
geom_bar(stat = "count", fill = "skyblue") +
labs(title = "Education Level Counts", x = "Education Level", y = "Count") +
theme_minimal()

#build of regression model
social factors and willingess to invest
m1 <- glm(willingness_to_invest ~ age_bracket + presence_of_latrine, sanitation_clean, family = binomial)
tbl_regression(m1, exponentiate = TRUE)

here is error
Error:
! y values must be 0 <= y <= 1
Backtrace:

stats::glm(...)
stats::glm.fit(...)
Execution halted

@larnsce @mianzg @sskorik01
